spring:
  data:
    mongodb:
      database: user-service
      host: 192.168.29.136
      password: admin
      port: 27017
      username: admin
      authentication-database: admin
      
  mail:
    host: smtp.gmail.com
    username: resumemanagementapp@gmail.com
    password: jbeczzezydqaiqlp
    port: 587
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true     
jwt:
  secret: g1eOO8+OfSnul5MbKFsi/1UHSm5AMs2fpAKrpOWli3Q=
  expirationDateInMs: 600000
  refreshExpirationDateInMs: 600000
        
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://eureka:eureka@localhost:8761/eureka/
  instance:
    hostname: localhost
    instance-id: ${spring.application.name} :${random.uuid}  
    
    
info:
  app:
    name: User Management Microservice
    description: SP Soft HRMS Application
    version: v1.0.0
    
management:
  endpoint:
    health:
      show-details: always
      
  info:
    env:
      enabled: true
  
